from pathlib import Path

def replace_once(source, old, new):
    assert source.count(old) == 1, repr(old)
    return source.replace(old, new, 1)

p = Path('src/components/JobCard.jsx')
s = p.read_text()
s = replace_once(s, 'import { useState } from "react";', 'import { useState } from "react";\nimport "./jobCardPhotoSummary.css";')
s = replace_once(s, '// Search keeps the same photo/summary card as related jobs, with video below it.', '// Search places its summary on the photograph; any YouTube stays below the card.')
s = replace_once(s, 'hideMedia = false, attachedVideo = false })', 'hideMedia = false, attachedVideo = false, videoPlacement })')
s = replace_once(s, '      data-guide={hideMedia ? undefined : "job-card"}', '      data-guide={hideMedia ? undefined : "job-card"}\n      className={hideMedia ? "job-card-summary-link" : videoPlacement === "below" ? "job-card-photo-summary" : undefined}')
s = replace_once(s, '<img loading={priority ? "eager" : "lazy"}', '<img className="job-card-cover" loading={priority ? "eager" : "lazy"}')
s = replace_once(s, '<div onAnimationEnd={()=>setPhotoPop(false)} style={{ width:"100%", height:photoHeight', '<div className="job-card-cover" onAnimationEnd={()=>setPhotoPop(false)} style={{ width:"100%", height:photoHeight')
s = replace_once(s, '<div style={{ padding: isList ? "10px 4px 0" : "8px 2px 0" }}>', '<div className="job-card-summary" style={{ padding: isList ? "10px 4px 0" : "8px 2px 0" }}>')
s = s.replace('//   黒グラデのオーバーレイは廃止＝全variantが同じ型（サイズだけ違う）。', '//   2026-10-06: さがす(videoPlacement="below")のみ写真内に文面を表示。他の面は従来配置。')
p.write_text(s)
p = Path('src/components/JobVideoCard.jsx')
s = p.read_text()
s = replace_once(s, 'height = 220, hideEndLabel, cardStyle })', 'height = 220, hideEndLabel, cardStyle, videoPlacement })')
s = replace_once(s, "className={`job-media-card${videoId ? ' job-video-card' : ' job-photo-card'}`}", "className={`job-media-card${videoId ? ' job-video-card' : ' job-photo-card'}${videoPlacement === 'below' && !videoId ? ' job-card-photo-summary' : ''}`}")
s = replace_once(s, '<div className="f-sans" style={{ display: \'flex\', alignItems: \'center\', flexWrap: \'wrap\', gap: 8, minHeight: 44, marginBottom: 6 }}>', '<div className="f-sans job-card-media-header" style={{ display: \'flex\', alignItems: \'center\', flexWrap: \'wrap\', gap: 8, minHeight: 44, marginBottom: 6 }}>')
p.write_text(s)
p = Path('scripts/search-card-photo-summary.mjs')
s = p.read_text()
s = replace_once(s, 'await page.evaluate(()=>window.qaRender([{...window.qaJobs?.[0],...{id:job.id}}]));', 'await page.evaluate(()=>{window.dispatchEvent(new Event("hashchange"));window.scrollTo(0,0);});\n              await page.waitForFunction(()=>!document.querySelector("iframe"));\n              await page.screenshot({path:"/tmp/photo-summary-mobile.png",fullPage:true});')
p.write_text(s)
print('Applied search-only summary-on-photo styling. Video, prices, data writes and other card variants unchanged.')
