import test from 'node:test';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import { mkdtemp,readFile,rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { build } from 'vite';
import react from '@vitejs/plugin-react';
const require=createRequire(import.meta.url);
const {JSDOM,VirtualConsole}=require(process.env.CB_TEST_NODE_MODULES?`${process.env.CB_TEST_NODE_MODULES}/jsdom`:'jsdom');
const root=fileURLToPath(new URL('../',import.meta.url));
const pause=ms=>new Promise(r=>setTimeout(r,ms));
const user='10000000-0000-4000-8000-000000000001', partner='10000000-0000-4000-8000-000000000002';
const app='20000000-0000-4000-8000-000000000001', past='20000000-0000-4000-8000-000000000002';
const button=(w,label)=>[...w.document.querySelectorAll('button')].find(el=>el.textContent.trim()===label);
async function until(fn,label){const end=Date.now()+5000;while(!fn()){assert.ok(Date.now()<end,`timed out: ${label}`);await pause(10);}}
async function fill(w,selector,value){const el=w.document.querySelector(selector);assert.ok(el,selector);Object.getOwnPropertyDescriptor(el.tagName==='TEXTAREA'?w.HTMLTextAreaElement.prototype:w.HTMLInputElement.prototype,'value').set.call(el,value);el.dispatchEvent(new w.Event('input',{bubbles:true}));await pause(10);}
function records(){return {
 applications:[{id:app,farmer_id:partner,worker_id:user,job_number:1311,status:'approved',terms_confirmed_worker_at:'2026-09-01',created_at:'2026-09-01T01:00:00Z'},{id:past,farmer_id:partner,worker_id:user,job_number:1200,status:'completed',created_at:'2026-08-01T00:00:00Z'}],
 jobs_public:[{job_number:1311,crop:'ブロッコリー',task:'播種',date_start:'2026-09-24',date_end:'2026-09-24',work_time:'10:00〜12:00'},{job_number:1200,crop:'にんじん',task:'収穫',date_start:'2026-08-24'}],
 employer_profiles_public:[{auth_id:partner,nickname:'農園サンプル',avatar_url:''}],worker_profiles:[{auth_id:user,nickname:'働き手サンプル',avatar_url:''}],
 messages:[{id:'30000000-0000-4000-8000-000000000001',application_id:app,sender_id:partner,body:'明日は集合場所でお待ちしています。',created_at:'2026-09-23T09:00:00Z',read_at:null},{id:'30000000-0000-4000-8000-000000000002',application_id:past,sender_id:partner,body:'ありがとうございました。',created_at:'2026-08-24T09:00:00Z',read_at:null}],
 chat_reads:[],admin_messages:[]};}
test('chat inbox, conversation, recovery and mobile viewport work together',async t=>{
 const output=await mkdtemp(path.join(tmpdir(),'cb-chat-'));let dom;const errors=[];
 try{
 await build({configFile:false,root,logLevel:'error',define:{'process.env.NODE_ENV':'"production"'},plugins:[{name:'chat-fixture',enforce:'pre',resolveId(id){if(/(?:^|\/)supabase(?:\.js)?$/.test(id))return path.join(root,'scripts/fixtures/chat/client.js');},transform(code,id){if(id.endsWith('/src/lib/chatMessaging.js'))return code.replace('CHAT_TIMEOUT_MS = 15000','CHAT_TIMEOUT_MS = 120');}},react()],build:{outDir:output,lib:{entry:path.join(root,'scripts/fixtures/chat/entry.jsx'),name:'ChatQA',formats:['iife'],fileName:'fixture',cssFileName:'fixture'},minify:false}});
 const script=await readFile(path.join(output,'fixture.iife.js'),'utf8'),css=await readFile(path.join(output,'fixture.css'),'utf8');
 function mount(settings={}){dom?.window.close();const vc=new VirtualConsole();vc.on('jsdomError',e=>{if(!/CSS|navigation/.test(e.message))errors.push(e.message);});vc.on('error',(...args)=>errors.push(args.join(' ')));dom=new JSDOM('<div id="root"></div>',{url:'https://chat.test/#/chats',runScripts:'dangerously',pretendToBeVisual:true,virtualConsole:vc});const w=dom.window;Object.assign(w,{qaUser:user,qaData:records(),qaUnread:{[app]:1},qaChannels:[],qaRequests:[],...settings,TextEncoder,TextDecoder});w.matchMedia=()=>({matches:false,addEventListener(){},removeEventListener(){}});w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=()=>{};w.visualViewport=Object.assign(new w.EventTarget(),{width:390,height:844,offsetLeft:0,offsetTop:0,scale:1});w.alert=value=>errors.push('alert: '+value);const style=w.document.createElement('style');style.textContent=css;w.document.head.append(style);w.eval(script);return w;}
 const input=w=>w.document.querySelector('textarea[aria-label="メッセージ"]');
 await t.test('inbox shows recent previews and filters by job, unread and lifecycle',async()=>{const w=mount();await until(()=>w.document.querySelectorAll('.chat-inbox-row').length===2,'rows');await until(()=>w.document.querySelector('.chat-row-preview')?.textContent.includes('明日は'),'preview');button(w,'終了').click();await until(()=>w.document.querySelectorAll('.chat-inbox-row').length===1,'past');assert.match(w.document.querySelector('.chat-inbox-row').textContent,/にんじん/);button(w,'すべて').click();await fill(w,'input[type=search]','1311');assert.equal(w.document.querySelectorAll('.chat-inbox-row').length,1);await fill(w,'input[type=search]','存在しない');assert.match(w.document.body.textContent,/該当する仕事の会話はありません/);button(w,'すべての会話を表示').click();await until(()=>w.document.querySelectorAll('.chat-inbox-row').length===2,'reset');assert.ok(button(w,'この画面を報告'));});
 await t.test('inbox load failures expose retry instead of claiming no conversations',async()=>{const w=mount({qaFailRead:'applications'});await until(()=>button(w,'再読み込み'),'retry');assert.doesNotMatch(w.document.body.textContent,/会話はここから始まります/);w.qaFailRead=null;button(w,'再読み込み').click();await until(()=>w.document.querySelectorAll('.chat-inbox-row').length===2,'recovered');});
 await t.test('keyboard, zoom and rotation keep both shell and closeable details in the visual viewport',async()=>{const w=mount({qaRoute:app});await until(()=>input(w)&&!input(w).disabled,'loaded');await fill(w,'textarea[aria-label="メッセージ"]','入力途中');const vv=w.visualViewport;Object.assign(vv,{width:320,height:290,offsetTop:155,offsetLeft:20,scale:1});vv.dispatchEvent(new w.Event('resize'));const room=w.document.querySelector('.chat-room');assert.equal(room.style.getPropertyValue('--chat-top'),'155px');assert.equal(room.style.getPropertyValue('--chat-height'),'290px');assert.equal(w.getComputedStyle(room).position,'fixed');const rules=[];function visit(list){for(const rule of list){if(rule.selectorText)rules.push(rule);if(rule.cssRules)visit(rule.cssRules);}}for(const sheet of w.document.styleSheets)visit(sheet.cssRules);assert.ok(rules.some(rule=>rule.selectorText==='header:where(.app-header)'));assert.equal(rules.some(rule=>rule.style.getPropertyPriority('padding')==='important'&&w.document.querySelector('.chat-room-header').matches(rule.selectorText)),false);button(w,'詳細').click();await until(()=>w.document.querySelector('[role=dialog]'),'details');assert.equal(w.document.querySelector('.chat-sheet-overlay').style.getPropertyValue('--chat-height'),'290px');w.document.querySelector('[aria-label="閉じる"]').click();await until(()=>!w.document.querySelector('[role=dialog]'),'close');assert.equal(input(w).value,'入力途中');button(w,'詳細').click();await until(()=>button(w,'仕事の内容を確認する →'),'job');button(w,'仕事の内容を確認する →').click();await until(()=>w.document.querySelector('[role=dialog][aria-label="仕事の内容"]'),'job sheet');w.document.querySelector('[aria-label="閉じる"]').click();await until(()=>!w.document.querySelector('[role=dialog]'),'job close');Object.assign(vv,{width:844,height:390,offsetTop:0,offsetLeft:0,scale:1});vv.dispatchEvent(new w.Event('resize'));assert.equal(room.style.getPropertyValue('--chat-width'),'844px');assert.ok(w.document.querySelector('[aria-label="メッセージ一覧に戻る"]'));});
 await t.test('drafts survive navigation, templates append without sending, Enter only adds a newline',async()=>{const w=mount({qaRoute:app});await until(()=>input(w)&&!input(w).disabled,'loaded');await fill(w,'textarea[aria-label="メッセージ"]','先に入力した文');button(w,'定型文').click();await until(()=>button(w,'持ち物'),'templates');button(w,'持ち物').click();await until(()=>input(w).value.includes('持ち物'),'append');assert.ok(input(w).value.startsWith('先に入力した文'));input(w).dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));assert.equal(w.qaRequests.filter(r=>r.op==='insert').length,0);w.qaNavigate(past);await until(()=>w.document.body.textContent.includes('この仕事は完了'),'past thread');w.qaNavigate(app);await until(()=>input(w)?.value.includes('持ち物'),'draft restored');assert.equal(w.qaData.messages.length,2);assert.equal(Object.keys(w.localStorage).some(k=>String(w.localStorage.getItem(k)).includes('先に入力した文')),false);});
 await t.test('lost send response and double clicks retry the same UUID exactly once',async()=>{const w=mount({qaRoute:app,qaSendMode:'lost'});await until(()=>input(w)&&!input(w).disabled,'loaded');await fill(w,'textarea[aria-label="メッセージ"]','受信済みでも二重送信しない');button(w,'送信').click();button(w,'送信')?.click();await until(()=>button(w,'同じ内容で再送'),'failed');assert.equal(input(w).value,'受信済みでも二重送信しない');assert.equal(input(w).readOnly,true);button(w,'同じ内容で再送').click();await until(()=>input(w).value==='','acknowledged');const sent=w.qaData.messages.filter(m=>m.body==='受信済みでも二重送信しない');assert.equal(sent.length,1);const requests=w.qaRequests.filter(r=>r.op==='insert');assert.equal(new Set(requests.map(r=>r.value.id)).size,1);assert.equal(w.document.querySelectorAll('.chat-bubble').length,2);});
 await t.test('send deadline unblocks controls and late results cannot contaminate another thread',async()=>{const w=mount({qaRoute:app,qaSendMode:'hold'});await until(()=>input(w)&&!input(w).disabled,'loaded');await fill(w,'textarea[aria-label="メッセージ"]','送信後に別の会話へ移動');button(w,'送信').click();await until(()=>button(w,'同じ内容で再送'),'bounded timeout');w.qaNavigate(past);await until(()=>w.document.body.textContent.includes('この仕事は完了'),'switched');w.qaResolveSend();await pause(30);assert.doesNotMatch(w.document.querySelector('.chat-messages').textContent,/送信後に別の会話へ移動/);w.qaNavigate(app);await until(()=>input(w)?.value==='','confirmed by fetch');assert.equal(w.qaData.messages.filter(m=>m.body==='送信後に別の会話へ移動').length,1);});
 await t.test('hidden conversations are not marked read and failure retains visible history',async()=>{const w=mount({qaRoute:app,qaFailRead:'messages'});Object.defineProperty(w.document,'visibilityState',{configurable:true,value:'hidden'});await until(()=>button(w,'再読み込み'),'read error');assert.equal(w.qaRequests.filter(r=>r.table==='messages'&&r.op==='update').length,0);w.qaFailRead=null;button(w,'再読み込み').click();await until(()=>w.document.querySelector('.chat-bubble'),'history recovered');assert.equal(w.qaRequests.filter(r=>r.table==='messages'&&r.op==='update').length,0);});
 await t.test('closed threads remain readable and cannot send; screen reports stay available',async()=>{const w=mount({qaRoute:past});await until(()=>w.document.body.textContent.includes('この仕事は完了'),'closed');assert.equal(input(w),null);assert.match(w.document.querySelector('.chat-messages').textContent,/ありがとうございました/);button(w,'詳細').click();await until(()=>button(w,'この画面を報告'),'screen report');let report;w.addEventListener('cb:open-support',event=>report=event.detail);button(w,'この画面を報告').click();assert.equal(report.view,'compose');assert.equal(report.topic,'chat');});
 await t.test('support chat also preserves failed messages and requires explicit send for multiline input',async()=>{const w=mount({qaRoute:'admin',qaSendMode:'lost'});await until(()=>w.document.querySelector('textarea')&&!w.document.querySelector('textarea').disabled,'support composer');await fill(w,'textarea','運営への相談\n二行目');const el=w.document.querySelector('textarea');el.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));assert.equal(w.qaData.admin_messages.length,0);button(w,'送信').click();await until(()=>button(w,'同じ内容で再送'),'support failure');button(w,'同じ内容で再送').click();await until(()=>el.value==='','support recovered');assert.equal(w.qaData.admin_messages.length,1);assert.ok(button(w,'この画面を報告'));});
 assert.deepEqual(errors,[]);
 }finally{dom?.window.close();await rm(output,{recursive:true,force:true});}
});
