CREATE OR REPLACE VIEW public.jobs_public AS
SELECT job_number,
    crop,
    task,
    prefecture,
    city,
    town,
    date_label,
    date_start,
    date_end,
    headcount,
    pay_type,
    hourly_wage,
    daily_wage,
    work_time,
    break_time,
    nearest_station,
    commute_time,
    job_exp,
    notes,
    belongings,
    cautions,
    danger_places,
    danger_tasks,
    photos,
    created_at,
    lat,
    lng,
    geo_radius_m,
    full_pay_guarantee
   FROM jobs
  WHERE status = 'open'::text;