-- 現在情報と契約時情報の分離（2026-08-02たきと確定指示）
-- account_holders を本人・法人情報の唯一の正とし、成立済み契約は terms_snapshot の凍結値を参照する。
-- ①契約成立（terms_snapshot 凍結）時に当事者名を snapshot 内へ追記（party_names）
-- ②contract_party_name は凍結値を優先参照（party_names の無い旧契約のみ現在値フォールバック）
-- ③account_holders の変更履歴（変更前後の値・日時・変更者・変更元）＝行動記録の憲法・柱1
-- ④entity_type / company_number は確定後の通常編集を禁止（初回設定は可・変更は運営のみ）
-- ⑤変更元タグ付き本人更新RPC update_account_holder_self（PostgRESTはリクエスト間でGUCを
--   持ち回れないため、set_config とUPDATEを同一トランザクションで行う関数が必要）

-- ① 凍結時に当事者名を追記。protect_terms_snapshot は old.terms_snapshot が not null の時のみ
--    改変を拒むため、null→値 の凍結遷移でこの追記を行っても衝突しない（定義を逐語確認済み）。
--    トリガー名は protect_terms_snapshot よりアルファベット順で先＝先に実行される。
create or replace function public.trg_enrich_terms_snapshot_party()
returns trigger language plpgsql security definer set search_path = public as $$
declare v_worker text; v_farmer text;
begin
  if old.terms_snapshot is null and new.terms_snapshot is not null
     and not (new.terms_snapshot ? 'party_names') then
    select nullif(btrim(full_name),'') into v_worker from public.account_holders where auth_id = new.worker_id;
    select nullif(btrim(full_name),'') into v_farmer from public.account_holders where auth_id = new.farmer_id;
    new.terms_snapshot := new.terms_snapshot || jsonb_build_object(
      'party_names', jsonb_build_object('worker', v_worker, 'farmer', v_farmer));
  end if;
  return new;
end; $$;

drop trigger if exists enrich_terms_snapshot_party on public.applications;
create trigger enrich_terms_snapshot_party
  before update on public.applications
  for each row execute function public.trg_enrich_terms_snapshot_party();

-- ② 成立済み契約の当事者名は凍結値を正とする。旧契約（party_names 無し）のみ現在値で代替
create or replace function public.contract_party_name(p_application_id uuid)
returns json language plpgsql stable security definer set search_path = public as $$
declare v_w uuid; v_f uuid; v_snap jsonb; v_name text; v_other uuid;
begin
  select worker_id, farmer_id, terms_snapshot into v_w, v_f, v_snap
    from public.applications where id = p_application_id;
  if v_w is null then return json_build_object('ok',false,'reason','not_found'); end if;
  if auth.uid() not in (v_w, v_f) then return json_build_object('ok',false,'reason','not_party'); end if;
  if v_snap is null then
    return json_build_object('ok',false,'reason','not_contracted',
      'message','契約が成立すると、お互いのお名前が表示されます');
  end if;
  v_other := case when auth.uid() = v_f then v_w else v_f end;
  v_name := nullif(btrim(coalesce(
    v_snap #>> array['party_names', case when v_other = v_w then 'worker' else 'farmer' end], '')), '');
  if v_name is null then
    -- 2026-08-02 より前の旧契約は凍結名が存在しないため、従来どおり現在値で代替
    select nullif(btrim(full_name),'') into v_name
      from public.account_holders where auth_id = v_other;
  end if;
  return json_build_object('ok', true, 'name', v_name);
end; $$;

-- ③ 変更履歴テーブル（変更のあった列のみ old/new を保存・当事者は改変不可）
create table if not exists public.account_holder_changes (
  id bigint generated by default as identity primary key,
  account_auth_id uuid not null,
  changed_at timestamptz not null default now(),
  changed_by uuid,                        -- auth.uid()。service role等の直接操作は null
  source text not null default 'direct',  -- 変更元（app.change_source。RPC経由なら画面名が入る）
  old_values jsonb not null,              -- {列名: 旧値} 変更のあった列のみ
  new_values jsonb not null               -- {列名: 新値} 変更のあった列のみ
);
alter table public.account_holder_changes enable row level security;
drop policy if exists "ahc self or admin read" on public.account_holder_changes;
create policy "ahc self or admin read" on public.account_holder_changes
  for select to authenticated
  using (auth.uid() = account_auth_id
         or exists (select 1 from public.app_admins a where a.auth_id = auth.uid()));
revoke all on public.account_holder_changes from anon, authenticated;
grant select on public.account_holder_changes to authenticated;

-- 履歴の改変・削除を全経路で拒否（trg_messages_history_lock と同じ二重の壁思想）
create or replace function public.trg_account_holder_changes_lock()
returns trigger language plpgsql as $$
begin
  raise exception '変更履歴は改変・削除できません';
end; $$;
drop trigger if exists account_holder_changes_lock on public.account_holder_changes;
create trigger account_holder_changes_lock
  before update or delete on public.account_holder_changes
  for each row execute function public.trg_account_holder_changes_lock();

-- 変更記録トリガー（security definer＝クライアントにINSERT権が無くても履歴は書ける）
create or replace function public.trg_log_account_holder_change()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  v_old jsonb := '{}'; v_new jsonb := '{}';
  v_cols text[] := array['full_name','postal_code','address','birth_date','entity_type',
    'contact_email','contact_phone','company_name','company_number'];
  c text; o jsonb; n jsonb;
begin
  o := to_jsonb(old); n := to_jsonb(new);
  foreach c in array v_cols loop
    if (o -> c) is distinct from (n -> c) then
      v_old := v_old || jsonb_build_object(c, o -> c);
      v_new := v_new || jsonb_build_object(c, n -> c);
    end if;
  end loop;
  if v_old = '{}'::jsonb then return new; end if;
  insert into public.account_holder_changes (account_auth_id, changed_by, source, old_values, new_values)
  values (new.auth_id, auth.uid(),
          coalesce(nullif(current_setting('app.change_source', true), ''), 'direct'),
          v_old, v_new);
  return new;
end; $$;
drop trigger if exists log_account_holder_change on public.account_holders;
create trigger log_account_holder_change
  after update on public.account_holders
  for each row execute function public.trg_log_account_holder_change();

-- ④ entity_type / company_number の通常編集禁止。
--    空→値（初回設定）は許可、確定後の変更は運営（app_admins）と非ログイン経路（service role＝運営の直接操作）のみ
create or replace function public.trg_lock_account_identity()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if (nullif(old.entity_type, '') is not null
        and old.entity_type is distinct from new.entity_type)
     or (nullif(old.company_number, '') is not null
        and old.company_number is distinct from new.company_number) then
    if auth.uid() is not null
       and not exists (select 1 from public.app_admins a where a.auth_id = auth.uid()) then
      raise exception '事業区分・法人番号は変更できません。変更が必要な場合は運営にお問い合わせください';
    end if;
  end if;
  return new;
end; $$;
drop trigger if exists lock_account_identity on public.account_holders;
create trigger lock_account_identity
  before update on public.account_holders
  for each row execute function public.trg_lock_account_identity();

-- ⑤ 変更元タグ付き本人更新RPC（SECURITY INVOKER＝own_update RLSがそのまま適用される）
create or replace function public.update_account_holder_self(p_patch jsonb, p_source text default 'app')
returns json language plpgsql security invoker set search_path = public as $$
declare
  v_allowed text[] := array['full_name','postal_code','address','contact_email',
    'contact_phone','company_name','birth_date'];
  k text; v_n int;
begin
  if auth.uid() is null then return json_build_object('ok',false,'reason','not_authenticated'); end if;
  if p_patch is null or jsonb_typeof(p_patch) <> 'object' then
    return json_build_object('ok',false,'reason','bad_patch');
  end if;
  for k in select jsonb_object_keys(p_patch) loop
    if not (k = any(v_allowed)) then
      return json_build_object('ok',false,'reason','key_not_allowed','key',k);
    end if;
  end loop;
  perform set_config('app.change_source', coalesce(nullif(btrim(p_source),''),'app'), true);
  update public.account_holders set
    full_name     = case when p_patch ? 'full_name'     then p_patch->>'full_name'     else full_name end,
    postal_code   = case when p_patch ? 'postal_code'   then p_patch->>'postal_code'   else postal_code end,
    address       = case when p_patch ? 'address'       then p_patch->>'address'       else address end,
    contact_email = case when p_patch ? 'contact_email' then p_patch->>'contact_email' else contact_email end,
    contact_phone = case when p_patch ? 'contact_phone' then p_patch->>'contact_phone' else contact_phone end,
    company_name  = case when p_patch ? 'company_name'  then p_patch->>'company_name'  else company_name end,
    birth_date    = case when p_patch ? 'birth_date'    then nullif(p_patch->>'birth_date','')::date else birth_date end
  where auth_id = auth.uid();
  get diagnostics v_n = row_count;
  return json_build_object('ok', v_n > 0, 'updated', v_n);
end; $$;
revoke all on function public.update_account_holder_self(jsonb, text) from public, anon;
grant execute on function public.update_account_holder_self(jsonb, text) to authenticated;
